Rename ECXXX algorithm and related functions to ESXXX
Appstractive/jwt-kt pull request #12
Opened 2024-10-29 08:01 UTC by sake

The ECDSA signer and verifier use an `alg` header with `EC256` instead of `ES256` (analogous for 384 and 512). 
This prevents processing of JWTs produced by other signers as they write and expect the standard conforming value.

This patch renames all of the occurrences of ECXXX to ESXXX.

2024-11-05 17:13 UTC, aschulz90 requested changes
Thanks, I didn't catch that! There's just an issue with a typo in the README, that will need to be fixed, and then I will merge it.

2024-11-05 17:13 UTC, aschulz90 commented on jwt-ecdsa/README.md
> +- E2512
```suggestion
- ES256
- ES384
- ES512
```

2024-11-08 08:00 UTC, sake commented on jwt-ecdsa/README.md
> +- E2512
Corrected, thanks for the hint.

2024-11-08 08:55 UTC, aschulz90 approved these changes

2024-11-08 08:56 UTC, aschulz90 commented
Thank you!

2024-11-08 08:56 UTC, merged